module.exports = [
    'container of pudding',
    'piece of gum',
    'screw',
    'sponge',
    'plush dinosaur',
    'stick',
    'leg warmers',
    'can of chili',
    'thread',
    'miniature portrait',
    'sponge',
    'cow',
    'pearl necklace',
    'bag of rubber bands',
    'computer',
    'sketch pad',
    'clothes',
    'pinecone',
    'snowglobe',
    'food',
    'key chain',
    'grid paper',
    'bottle of syrup',
    'rusty nail',
    'box of tissues',
    'video games',
    'mouse pad',
    'rock',
    'computer',
    'bottle of water',
    'hair ribbon',
    'rabbit',
    'salt shaker',
    'shoes',
    'shovel',
    'spectacles',
    'shirt button',
    'roll of masking tape',
    'tooth pick',
    'bag',
    'sofa',
    'fishing hook',
    'eraser',
    'paintbrush',
    'ladle',
    'feather',
    'dove',
    'tweezers',
    'hammer',
    'spoon',
    'pair of earrings',
    'nail',
    'pair of glasses',
    'glow stick',
    'button',
    'straw',
    'wrench',
    'teddies',
    'bottle of lotion',
    'glass',
    'kitchen knife',
    'bell',
    'candy cane',
    'can of chili',
    'bookmark',
    'balloon',
    'candle',
    'spool of string',
    'cucumber',
    'purse/bag',
    'miniature portrait',
    'keychain',
    'box',
    'paperclip',
    'magnifying glass',
    'rope',
    'cow',
    'rock',
    'wireless control',
    'shoes',
    'pair of tongs',
    'mobile phone',
    'pants',
    'can of beans',
    'whale',
    'cat',
    'bag',
    'tube of lip balm',
    'clothes',
    'bandana',
    'bandana',
    'card',
    'handbasket',
    'paintbrush',
    'marble',
    'bookmark',
    'wine glass',
    'canteen',
    'acorn',
    'mouse pad',
    'bread',
    'giraffe',
    'shirt',
    'paper',
    'dictionary',
    'egg beater',
    'thread',
    'puddle',
    'tissue box',
    'rolling pin',
    'toilet',
    'box of chalk',
    'hand bag',
    'harmonica',
    'box of chocolates',
    'spool of wire',
    'sandglass',
    'trash bag',
    'boom box',
    'flowers'
  ]